version: '3.3' # specify docker-compose version

services:
      
  testdb:
    container_name:  testdb
    image: mysql
    ports:
      - "3706:3706"
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
    volumes:
      - ./data/mysqldb:/var/lib/mysql

  
    